name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  able:
    path: ../../able
  built_value_generator: ^8.11.1
  build_runner: ^2.7.0

flutter:
  uses-material-design: true